apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: failure-exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.19.0
  name: failure-exporter
  namespace: monitoring
spec:
  spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: failure-exporter
      app.kubernetes.io/part-of: kube-prometheus
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: failure-exporter
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: failure-exporter
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: 0.19.0
    spec:
      containers:
      - image: zenghaocq/failure-exporter:0.2
        imagePullPolicy: IfNotPresent
        name: failure-exporter
        ports:
        - containerPort: 8000
          name: http
        args:
        - --start=30
        - --period=20
        - --failureTypes=3
