apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: failure-exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.19.0
  name: failure-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 8000
    targetPort: http
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: failure-exporter
    app.kubernetes.io/part-of: kube-prometheus
